host: localhost
dbName: streaming
collectionName: outletProjection
fields:
  - generator: name
    name: firstName
    data:
      numberOfWords: 3
  - generator: name
    name: lastName
    data:
      numberOfWords: 3
  - generator: bool
    name: isActive
    data:
      trueWeight: 98