host: localhost
dbName: mogen
collectionName: outletProjection
nRows: 500
fields:
  - generator: name
    name: firstName
    data:
      options:
        - "Andy"
        - "Carol"
        - "Steinsberg"
        - "Kole"
        - "Ken"
        - "Kenny"
        - "Tham"
        - "Beatric"
  - generator: name
    name: lastName
    data:
      options:
        - "Andy"
        - "Carol"
        - "Steinsberg"
        - "Kole"
        - "Ken"
        - "Kenny"
        - "Tham"
        - "Beatric"
  - generator: bool
    name: isActiveIndexed
    index: true
    data:
      trueWeight: 98
  - generator: bool
    name: isActiveNonIndexed
    data:
      trueWeight: 98